
export const weatherImages = {
    'Partly cloudy': require('../assets/images/partlycloudy.png'),
    'Thundery outbreaks possible': require('../assets/images/heavyrain.png'),
    'Moderate rain': require('../assets/images/moderaterain.png'),
    'Patchy rain possible': require('../assets/images/moderaterain.png'),
    'Sunny': require('../assets/images/sun.png'),
    'Clear': require('../assets/images/sun.png'),
    'Overcast': require('../assets/images/cloud.png'),
    'Cloudy': require('../assets/images/cloud.png'),
    'Light rain': require('../assets/images/moderaterain.png'),
    'Light drizzle': require('../assets/images/moderaterain.png'),
    'Moderate rain at times': require('../assets/images/moderaterain.png'),
    'Heavy rain': require('../assets/images/heavyrain.png'),
    'Heavy rain at times': require('../assets/images/heavyrain.png'),
    'Moderate or heavy freezing rain': require('../assets/images/heavyrain.png'),
    'Moderate or heavy rain shower': require('../assets/images/heavyrain.png'),
    'Moderate or heavy rain with thunder': require('../assets/images/heavyrain.png'),
    'Mist': require('../assets/images/mist.png'),
    'Fog': require('../assets/images/mist.png'),
    'other': require('../assets/images/moderaterain.png')
}

export const backgroundImages = {
    'other': require('../assets/images/bgimg.jpg'),
    'Fog': require('../assets/images/fog_bgimg.png'),
    'Cloudy': require('../assets/images/cloudy_bgimg.png'),
    'Overcast': require('../assets/images/cloudy_bgimg.png'),
    'Moderate or heavy freezing rain': require('../assets/images/freeze_bgimg.png'),
    'Partly cloudy': require('../assets/images/partlycloudy_bgimg.png'),
    'Light rain': require('../assets/images/rainy_bgimg.png'),
    'Light drizzle': require('../assets/images/rainy_bgimg.png'),
    'Moderate rain at times': require('../assets/images/heavyrain_bgimg.png'),
    'Heavy rain': require('../assets/images/heavyrain_bgimg.png'),
    'Heavy rain at times': require('../assets/images/heavyrain_bgimg.png'),
    'Moderate or heavy freezing rain': require('../assets/images/freeze_bgimg.png'),
    'Moderate or heavy rain shower': require('../assets/images/heavyrain_bgimg.png'),
    'Sunny': require('../assets/images/sunny_bgimg.png'),
    'Thundery outbreaks possible': require('../assets/images/thunderstorm_bgimg.png'),
    'Moderate or heavy rain with thunder': require('../assets/images/thunderstorm_bgimg.png'),
    'Patchy light rain with thunder': require('../assets/images/heavyrain_bgimg.png'),
}